version: "3"
services:
  mysql:
    image: mysql:5.7.30
    environment:
      MYSQL_DATABASE: "openbazaarcom"
      MYSQL_USER: "root"
      MYSQL_ROOT_PASSWORD: "pass"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    ports:
      - 3306:3306
  migration:
    image: migrate/migrate
    links:
      - mysql
    depends_on:
      - mysql
    volumes:
      - ./scripts/migrations:/migrations
  webapp:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      OPENBAZAAR_BASE_URL: "http://localhost:8000"
    ports:
      - "8000:80"