<?php

function asset_url()
{
	return base_url() . 'assets/';
}

function market_price($coinType)
{
	$ticker = loadFile("https://ticker.openbazaar.org/api");
	$ticker = json_decode($ticker);
	return "Ƀ" . number_format(1 / $ticker->{$coinType}->last * $ticker->BTC->last, 5);
}

function convert_price($amount, $from, $to, $precision = 8)
{
	if($from=="") {
		return;
	}
	
	$CI = & get_instance();
	$CI->load->driver('cache', array(
		'adapter' => 'apc',
		'backup' => 'file'
	));
	$ob_ticker = $CI->cache->get('ob_ticker');
	if ($ob_ticker == "") {
		$ob_ticker = json_decode(loadFile("https://ticker.openbazaar.org/api"));
	}
	$e = $CI->cache->file->save('ob_ticker', $ob_ticker, 300);
	
	// Check if crypto
	$is_crypto = isset($ob_ticker->$from->type) && ($ob_ticker->$from->type == "crypto");
	
	if($is_crypto) {
		// Go from crypto to BTC to desired currency
		$crypto_in_btc = (1/$ob_ticker->$from->last);

		return $ob_ticker->$to->last * ($crypto_in_btc * $amount);
		
		
	} else {
		// Go from USD to currency
		$bitcoin_in_from_currency = $ob_ticker->$from->last;
		return (($amount / $bitcoin_in_from_currency)/100) * $ob_ticker->$to->last;
	}

}

function get_market_price($coinType, $precision = 8)
{
	$CI = & get_instance();
	$CI->load->driver('cache', array(
		'adapter' => 'apc',
		'backup' => 'file'
	));
	$ob_ticker = $CI->cache->get('ob_ticker');
	if ($ob_ticker == "") {
		$ob_ticker = json_decode(loadFile("https://ticker.openbazaar.org/api"));
	}

	$e = $CI->cache->file->save('ob_ticker', $ob_ticker, 300);
	return $ob_ticker->$coinType->last;
}

function get_http_response_code($url)
{
	$headers = get_headers($url);
	return substr($headers[0], 9, 3);
}

function get_profile($peerID)
{
	$CI = & get_instance();
	$CI->load->driver('cache', array(
		'adapter' => 'apc',
		'backup' => 'file'
	));
	$profile_load = $CI->cache->get('profile_' . $peerID);
	if ($profile_load == "") {
		/*
		if(get_http_response_code("https://gateway.ob1.io/ob/profile/".$peerID."?usecache=true") != "200"){
		$profile_load = "{}";
		}else{
		*/
		$ctx = stream_context_create(array(
			'http' => array(
				'timeout' => 10
			)
		));
		$profile_load = @loadFile("https://gateway.ob1.io/ob/profile/" . $peerID."?usecache=true");

		// 	    }

		$CI->cache->file->save('profile_' . $peerID, $profile_load, 900); // 15 minutes cache
	}

	return json_decode($profile_load);
}

function get_crypto_listings() {
	$CI = & get_instance();
	$CI->load->driver('cache', array(
		'adapter' => 'apc',
		'backup' => 'file'
	));
	$listings = $CI->cache->get('crypto_listings');

	if ($listings == "") {
		$listings = @loadFile("https://search.ob1.io/listings/random?type=cryptocurrency&size=5");		
		$CI->cache->file->save('crypto_listings', $listings, 60); // 60 minutes cache
	}
	$listings = json_decode($listings);
	
	
	return $listings;

}

function get_verified_mods() {
	
	$CI = & get_instance();
	$CI->load->driver('cache', array(
		'adapter' => 'apc',
		'backup' => 'file'
	));
	$mods = $CI->cache->get('verified_mods');

	if ($mods == "") {
		$mods = @loadFile("https://search.ob1.io/verified_moderators");		
		$CI->cache->file->save('verified_mods', $mods, 5400); // 60 minutes cache
	}
	$mods = json_decode($mods);
	
	$verified_mods = array();
	foreach($mods->moderators as $mod) {
		array_push($verified_mods, $mod->peerID);
	}
	return $verified_mods;
	
}

function rutime($ru, $rus, $index) {
    return ($ru["ru_$index.tv_sec"]*1000 + intval($ru["ru_$index.tv_usec"]/1000))
     -  ($rus["ru_$index.tv_sec"]*1000 + intval($rus["ru_$index.tv_usec"]/1000));
}

function get_listings($peerID)
{
	$CI = & get_instance();
	$CI->load->driver('cache', array(
		'adapter' => 'apc',
		'backup' => 'file'
	));
	$load = $CI->cache->get('listings_' . $peerID);
	
	if ($load == "") {
		$ctx = stream_context_create(array(
			'http' => array(
				'timeout' => 10
			)
		));
		$rustart = getrusage();
		$load = @loadFile("https://gateway.ob1.io/ob/listings/" . $peerID ."?usecache=true", 0, $ctx);
		$ru = getrusage();
		
		if($load != "") {
			$CI->cache->file->save('listings_' . $peerID, $load, 900); // 15 minutes cache
		}		
	}
	
	// Check if file failed
	$load_json = json_decode($load);
	if(isset($load_json->reason)) {
		$load = "";
	}
		
	$load = ($load == "") ? "[]" : $load;

	return json_decode($load);
}

function get_listing($peerID, $slug)
{
	$CI = & get_instance();
	$CI->load->driver('cache', array(
		'adapter' => 'apc',
		'backup' => 'file'
	));
	$listing_load = $CI->cache->get('listing_' . $slug);
	if ($listing_load == "") {
		$listing_load = @loadFile("https://gateway.ob1.io/ob/listing/" . $peerID . "/" . $slug);
		$CI->cache->file->save('listing_' . $slug, $listing_load, 5400); // 60 minutes cache
	}

	return json_decode($listing_load);
}

function contract_type_to_friendly($type)
{
	switch ($type) {
	case "PHYSICAL_GOOD":
		return "Physical Good";
		break;

	case "DIGITAL_GOOD":
		return "Digital Good";
		break;

	case "SERVICE":
		return "Service";
		break;

	case "CRYPTOCURRENCY":
		return "Cryptocurrency";
		break;

	default:
		return "";
	}
}

function condition_to_friendly($condition)
{
	switch ($condition) {
	case "NEW":
		return "New";
		break;

	case "USED_EXCELLENT":
		return "Used - Excellent";
		break;

	case "USED_GOOD":
		return "Used - Good";
		break;

	case "USED_POOR":
		return "Used - Poor";
		break;

	case "REFURBISHED":
		return "Refurbished";
		break;

	default:
		return "";
	}
}

function set_new_url($url_params, $name, $value)
{

	// if(isset($url_params[$name])) {

	$url_params[$name] = urlencode($value);

	// }

	$URI = http_build_query($url_params);
	$uri_parts = explode('?', $_SERVER['REQUEST_URI'], 2);
	return "//$_SERVER[HTTP_HOST]$uri_parts[0]?$URI";
}

function get_language()
{
	$locale = locale_accept_from_http($_SERVER['HTTP_ACCEPT_LANGUAGE']);
	echo $locale;
}

function ticker_to_symbol($ticker)
{
	$currency_symbols = array(
		'AED' => '&#1583;.&#1573;', // ?
		'BTC' => 'Ƀ',
		'AFN' => '&#65;&#102;',
		'ALL' => '&#76;&#101;&#107;',
		'AMD' => '',
		'ANG' => '&#402;',
		'AOA' => '&#75;&#122;', // ?
		'ARS' => '&#36;',
		'AUD' => '&#36;',
		'AWG' => '&#402;',
		'AZN' => '&#1084;&#1072;&#1085;',
		'BAM' => '&#75;&#77;',
		'BBD' => '&#36;',
		'BDT' => '&#2547;', // ?
		'BGN' => '&#1083;&#1074;',
		'BHD' => '.&#1583;.&#1576;', // ?
		'BIF' => '&#70;&#66;&#117;', // ?
		'BMD' => '&#36;',
		'BND' => '&#36;',
		'BOB' => '&#36;&#98;',
		'BRL' => '&#82;&#36;',
		'BSD' => '&#36;',
		'BTN' => '&#78;&#117;&#46;', // ?
		'BWP' => '&#80;',
		'BYR' => '&#112;&#46;',
		'BZD' => '&#66;&#90;&#36;',
		'CAD' => '&#36;',
		'CDF' => '&#70;&#67;',
		'CHF' => '&#67;&#72;&#70;',
		'CLF' => '', // ?
		'CLP' => '&#36;',
		'CNY' => '&#165;',
		'COP' => '&#36;',
		'CRC' => '&#8353;',
		'CUP' => '&#8396;',
		'CVE' => '&#36;', // ?
		'CZK' => '&#75;&#269;',
		'DJF' => '&#70;&#100;&#106;', // ?
		'DKK' => '&#107;&#114;',
		'DOP' => '&#82;&#68;&#36;',
		'DZD' => '&#1583;&#1580;', // ?
		'EGP' => '&#163;',
		'ETB' => '&#66;&#114;',
		'EUR' => '&#8364;',
		'FJD' => '&#36;',
		'FKP' => '&#163;',
		'GBP' => '&#163;',
		'GEL' => '&#4314;', // ?
		'GHS' => '&#162;',
		'GIP' => '&#163;',
		'GMD' => '&#68;', // ?
		'GNF' => '&#70;&#71;', // ?
		'GTQ' => '&#81;',
		'GYD' => '&#36;',
		'HKD' => '&#36;',
		'HNL' => '&#76;',
		'HRK' => '&#107;&#110;',
		'HTG' => '&#71;', // ?
		'HUF' => '&#70;&#116;',
		'IDR' => '&#82;&#112;',
		'ILS' => '&#8362;',
		'INR' => '&#8377;',
		'IQD' => '&#1593;.&#1583;', // ?
		'IRR' => '&#65020;',
		'ISK' => '&#107;&#114;',
		'JEP' => '&#163;',
		'JMD' => '&#74;&#36;',
		'JOD' => '&#74;&#68;', // ?
		'JPY' => '&#165;',
		'KES' => '&#75;&#83;&#104;', // ?
		'KGS' => '&#1083;&#1074;',
		'KHR' => '&#6107;',
		'KMF' => '&#67;&#70;', // ?
		'KPW' => '&#8361;',
		'KRW' => '&#8361;',
		'KWD' => '&#1583;.&#1603;', // ?
		'KYD' => '&#36;',
		'KZT' => '&#1083;&#1074;',
		'LAK' => '&#8365;',
		'LBP' => '&#163;',
		'LKR' => '&#8360;',
		'LRD' => '&#36;',
		'LSL' => '&#76;', // ?
		'LTL' => '&#76;&#116;',
		'LVL' => '&#76;&#115;',
		'LYD' => '&#1604;.&#1583;', // ?
		'MAD' => '&#1583;.&#1605;.', //?
		'MDL' => '&#76;',
		'MGA' => '&#65;&#114;', // ?
		'MKD' => '&#1076;&#1077;&#1085;',
		'MMK' => '&#75;',
		'MNT' => '&#8366;',
		'MOP' => '&#77;&#79;&#80;&#36;', // ?
		'MRO' => '&#85;&#77;', // ?
		'MUR' => '&#8360;', // ?
		'MVR' => '.&#1923;', // ?
		'MWK' => '&#77;&#75;',
		'MXN' => '&#36;',
		'MYR' => '&#82;&#77;',
		'MZN' => '&#77;&#84;',
		'NAD' => '&#36;',
		'NGN' => '&#8358;',
		'NIO' => '&#67;&#36;',
		'NOK' => '&#107;&#114;',
		'NPR' => '&#8360;',
		'NZD' => '&#36;',
		'OMR' => '&#65020;',
		'PAB' => '&#66;&#47;&#46;',
		'PEN' => '&#83;&#47;&#46;',
		'PGK' => '&#75;', // ?
		'PHP' => '&#8369;',
		'PKR' => '&#8360;',
		'PLN' => '&#122;&#322;',
		'PYG' => '&#71;&#115;',
		'QAR' => '&#65020;',
		'RON' => '&#108;&#101;&#105;',
		'RSD' => '&#1044;&#1080;&#1085;&#46;',
		'RUB' => '&#1088;&#1091;&#1073;',
		'RWF' => '&#1585;.&#1587;',
		'SAR' => '&#65020;',
		'SBD' => '&#36;',
		'SCR' => '&#8360;',
		'SDG' => '&#163;', // ?
		'SEK' => '&#107;&#114;',
		'SGD' => '&#36;',
		'SHP' => '&#163;',
		'SLL' => '&#76;&#101;', // ?
		'SOS' => '&#83;',
		'SRD' => '&#36;',
		'STD' => '&#68;&#98;', // ?
		'SVC' => '&#36;',
		'SYP' => '&#163;',
		'SZL' => '&#76;', // ?
		'THB' => '&#3647;',
		'TJS' => '&#84;&#74;&#83;', // ? TJS (guess)
		'TMT' => '&#109;',
		'TND' => '&#1583;.&#1578;',
		'TOP' => '&#84;&#36;',
		'TRY' => '&#8356;', // New Turkey Lira (old symbol used)
		'TTD' => '&#36;',
		'TWD' => '&#78;&#84;&#36;',
		'TZS' => '',
		'UAH' => '&#8372;',
		'UGX' => '&#85;&#83;&#104;',
		'USD' => '&#36;',
		'UYU' => '&#36;&#85;',
		'UZS' => '&#1083;&#1074;',
		'VEF' => '&#66;&#115;',
		'VND' => '&#8363;',
		'VUV' => '&#86;&#84;',
		'WST' => '&#87;&#83;&#36;',
		'XAF' => '&#70;&#67;&#70;&#65;',
		'XCD' => '&#36;',
		'XDR' => '',
		'XOF' => '',
		'XPF' => '&#70;',
		'YER' => '&#65020;',
		'ZAR' => '&#82;',
		'ZMK' => '&#90;&#75;', // ?
		'ZWL' => '&#90;&#36;',
	);
	if (!array_key_exists($ticker, $currency_symbols)) {
		return $currency_symbols["BTC"];
	}
	else {
		return $currency_symbols[$ticker];
	}
}

function get_coin_amount($coinType) {
	if(in_array($coinType, array("BCH", "BTC"))) {
		return 100000000;							
	} else {
		return 1;
	}
}

function pretty_price($price, $currency, $digits=2)
{
	$user_currency = (isset($_COOKIE['currency'])) ? $_COOKIE['currency'] : "BTC";
	$symbol = ticker_to_symbol($currency);
	$user_symbol = ticker_to_symbol($user_currency);
	
	if ($user_currency != "BTC") {
		
		if(in_array($currency, array("BTC", "BCH"))) {
			$amount = convert_price($price/100000000, $currency, $user_currency);
			
		} else {
			$amount = convert_price($price, $currency, $user_currency);
		}
				
		if($amount >= 0.01) {
			$formatted_amount = money_format("%.2n", $amount);
			$digits = 2;	
		} else {
			$formatted_amount = money_format("%.".$digits."n", $amount);
		}

		$formatted_amount = number_format($formatted_amount, $digits);
		
		return $user_symbol . $formatted_amount;
	}
	else {
		$amount = preg_replace('/0{1,2}$/', '', number_format(convert_price($price, $currency, $user_currency) , 8));
		return $user_symbol . $amount;
	}
}

function sani_input($url) {
	return filter_var($url, FILTER_SANITIZE_STRING);
}

function ip_info($ip = NULL, $purpose = "location", $deep_detect = TRUE) {
    $output = NULL;
    if (filter_var($ip, FILTER_VALIDATE_IP) === FALSE) {
        $ip = $_SERVER["REMOTE_ADDR"];
        if ($deep_detect) {
            if (filter_var(@$_SERVER['HTTP_X_FORWARDED_FOR'], FILTER_VALIDATE_IP))
                $ip = $_SERVER['HTTP_X_FORWARDED_FOR'];
            if (filter_var(@$_SERVER['HTTP_CLIENT_IP'], FILTER_VALIDATE_IP))
                $ip = $_SERVER['HTTP_CLIENT_IP'];
        }
    }

    $purpose    = str_replace(array("name", "\n", "\t", " ", "-", "_"), NULL, strtolower(trim($purpose)));
    $support    = array("country", "countrycode", "state", "region", "city", "location", "address");
    $continents = array(
        "AF" => "Africa",
        "AN" => "Antarctica",
        "AS" => "Asia",
        "EU" => "Europe",
        "OC" => "Australia (Oceania)",
        "NA" => "North America",
        "SA" => "South America"
    );
    if (filter_var($ip, FILTER_VALIDATE_IP) && in_array($purpose, $support)) {
        $ipdat = @json_decode(loadFile("http://www.geoplugin.net/json.gp?ip=" . $ip));
        if (@strlen(trim($ipdat->geoplugin_countryCode)) == 2) {
            switch ($purpose) {
                case "location":
                    $output = array(
                        "city"           => @$ipdat->geoplugin_city,
                        "state"          => @$ipdat->geoplugin_regionName,
                        "country"        => @$ipdat->geoplugin_countryName,
                        "country_code"   => @$ipdat->geoplugin_countryCode,
                        "continent"      => @$continents[strtoupper($ipdat->geoplugin_continentCode)],
                        "continent_code" => @$ipdat->geoplugin_continentCode
                    );
                    break;
                case "address":
                    $address = array($ipdat->geoplugin_countryName);
                    if (@strlen($ipdat->geoplugin_regionName) >= 1)
                        $address[] = $ipdat->geoplugin_regionName;
                    if (@strlen($ipdat->geoplugin_city) >= 1)
                        $address[] = $ipdat->geoplugin_city;
                    $output = implode(", ", array_reverse($address));
                    break;
                case "city":
                    $output = @$ipdat->geoplugin_city;
                    break;
                case "state":
                    $output = @$ipdat->geoplugin_regionName;
                    break;
                case "region":
                    $output = @$ipdat->geoplugin_regionName;
                    break;
                case "country":
                    $output = @$ipdat->geoplugin_countryName;
                    break;
                case "countrycode":
                    $output = @$ipdat->geoplugin_countryCode;
                    break;
            }
        }
    }
    return $output;
}

function coin_to_icon($coin) {
	$coin_matching_dict = array(
		"42" => "42-coin",
		"300" => "300 Token",
		"611" => "SixEleven",
		"808" => "808Coin",
		"888" => "OctoCoin",
		"1337" => "Elite",
		"$$$" => "Money",
		'$PAC' => "PACcoin",
		"0xBTC" => "0xBitcoin",
		"1ST" => "FirstBlood",
		"1WO" => "1World",
		"2GIVE" => "2GIVE",
		"8BIT" => "8Bit",
		"AAC" => "Acute Angle Cloud",
		"ABC" => "Alphabit",
		"ABJC" => "Abjcoin Commerce",
		"ABT" => "Arcblock",
		"ABY" => "ArtByte",
		"ABYSS" => "The Abyss",
		"AC" => "AsiaCoin",
		"AC3" => "AC3",
		"ACAT" => "Alphacat",
		"ACC" => "Accelerator Network",
		"ACE" => "ACE (TokenStars)",
		"ACES" => "Aces",
		"ACN" => "Avoncoin",
		"ACOIN" => "Acoin",
		"ACP" => "AnarchistsPrime",
		"ACT" => "Achain",
		"ADA" => "Cardano",
		"ADB" => "adbank",
		"ADC" => "AudioCoin",
		"ADCN" => "Asiadigicoin",
		"ADH" => "AdHive",
		"ADI" => "Aditus",
		"ADK" => "Aidos Kuneen",
		"ADST" => "AdShares",
		"ADT" => "adToken",
		"ADX" => "AdEx",
		"ADZ" => "Adzcoin",
		"AE" => "Aeternity",
		"AEG" => "Aegeus",
		"AEON" => "Aeon",
		"AERM" => "Aerium",
		"AGI" => "SingularityNET",
		"AHT" => "Bowhead",
		"AI" => "POLY AI",
		"AIB" => "Advanced Internet Blocks",
		"AID" => "AidCoin",
		"AIDOC" => "AI Doctor",
		"AION" => "Aion",
		"AIR" => "AirToken",
		"AIT" => "AICHAIN",
		"AIX" => "Aigang",
		"AKY" => "Akuya Coin",
		"ALIS" => "ALIS",
		"ALL" => "Allion",
		"ALQO" => "ALQO",
		"ALT" => "Altcoin",
		"ALX" => "ALAX",
		"AMB" => "Ambrosus",
		"AMLT" => "AMLT",
		"AMM" => "MicroMoney",
		"AMMO" => "Ammo Reloaded",
		"AMN" => "Amon",
		"AMP" => "Synereo",
		"AMS" => "AmsterdamCoin",
		"ANC" => "Anoncoin",
		"ANI" => "Animecoin",
		"ANT" => "Aragon",
		"ANTX" => "Antimatter",
		"AOA" => "Aurora",
		"APH" => "Aphelion",
		"APIS" => "APIS",
		"APPC" => "AppCoins",
		"APR" => "APR Coin",
		"APX" => "APX",
		"ARB" => "ARbit",
		"ARC" => "Advanced Technology Coin",
		"ARCO" => "AquariusCoin",
		"ARCT" => "ArbitrageCT",
		"ARDR" => "Ardor",
		"ARG" => "Argentum",
		"ARGUS" => "Argus",
		"ARI" => "Aricoin",
		"ARK" => "Ark",
		"ARN" => "Aeron",
		"ART" => "Maecenas",
		"ARY" => "Block Array",
		"ASAFE2" => "AllSafe",
		"ASN" => "Aseancoin",
		"AST" => "AirSwap",
		"ASTRO" => "Astro",
		"AT" => "AWARE",
		"ATB" => "ATBCoin",
		"ATC" => "Arbitracoin",
		"ATL" => "ATLANT",
		"ATM" => "ATMChain",
		"ATMC" => "ATMCoin",
		"ATMI" => "Atonomi",
		"ATMOS" => "Atmos",
		"ATN" => "ATN",
		"ATOM" => "Atomic Coin",
		"ATS" => "Authorship",
		"ATX" => "Artex Coin",
		"AU" => "AurumCoin",
		"AUC" => "Auctus",
		"AUR" => "Auroracoin",
		"AURA" => "Aurora DAO",
		"AUTO" => "Cube",
		"AV" => "AvatarCoin",
		"AVA" => "Travala",
		"AVH" => "Animation Vision Cash",
		"AVT" => "Aventus",
		"AXIOM" => "Axiom",
		"AXP" => "aXpire",
		"B2B" => "B2BX",
		"B2X" => "SegWit2x",
		"B@" => "Bankcoin",
		"BANCA" => "Banca",
		"BANK" => "Bank Coin",
		"BAS" => "BitAsean",
		"BAT" => "Basic Attention Token",
		"BAX" => "BABB",
		"BAY" => "BitBay",
		"BBC" => "TraDove B2BCoin",
		"BBI" => "BelugaPay",
		"BBN" => "Banyan Network",
		"BBO" => "Bigbom",
		"BBP" => "BiblePay",
		"BBR" => "Boolberry",
		"BCA" => "Bitcoin Atom",
		"BCC" => "BitConnect",
		"BCD" => "Bitcoin Diamond",
		"BCDN" => "BlockCDN",
		"BCF" => "Bitcoin Fast",
		"BCH" => "Bitcoin Cash",
		"BCI" => "Bitcoin Interest",
		"BCN" => "Bytecoin",
		"BCO" => "BridgeCoin",
		"BCPT" => "BlockMason Credit Protocol",
		"BCX" => "BitcoinX",
		"BCY" => "Bitcrystals",
		"BDG" => "BitDegree",
		"BDL" => "Bitdeal",
		"BEE" => "Bee Token",
		"BELA" => "Bela",
		"BENJI" => "BenjiRolls",
		"BERN" => "BERNcash",
		"BERRY" => "Rentberry",
		"BET" => "DAO.Casino",
		"BETR" => "BetterBetting",
		"BEZ" => "Bezop",
		"BFT" => "BnkToTheFuture",
		"BIG" => "BigONE Token",
		"BIGUP" => "BigUp",
		"BIO" => "BioCoin",
		"BIOB" => "BioBar",
		"BIP" => "BipCoin",
		"BIRDS" => "Birds",
		"BIS" => "Bismuth",
		"BIT" => "First Bitcoin",
		"BITB" => "Bean Cash",
		"BITBTC" => "bitBTC",
		"BITCF" => "First Bitcoin Capital",
		"BITCNY" => "bitCNY",
		"BITEUR" => "bitEUR",
		"BITG" => "Bitcoin Green",
		"BITGOLD" => "bitGold",
		"BITOK" => "Bitok",
		"BITS" => "Bitstar",
		"BITSILVER" => "bitSilver",
		"BITUSD" => "bitUSD",
		"BIX" => "Bibox Token",
		"BKBT" => "BeeKan",
		"BKX" => "Bankex",
		"BLAZR" => "BlazerCoin",
		"BLC" => "Blakecoin",
		"BLK" => "BlackCoin",
		"BLN" => "Bolenum",
		"BLOCK" => "Blocknet",
		"BLT" => "Bloom",
		"BLU" => "BlueCoin",
		"BLUE" => "Blue Protocol",
		"BLZ" => "Bluzelle",
		"BMC" => "Blackmoon",
		"BMH" => "BlockMesh",
		"BMX" => "BitMart Token",
		"BNB" => "Binance Coin",
		"BNK" => "Bankera",
		"BNT" => "Bancor",
		"BNTY" => "Bounty0x",
		"BNX" => "BnrtxCoin",
		"BOAT" => "BOAT",
		"BOB" => "Bob's Repair",
		"BOE" => "Bodhi [ETH]",
		"BOLI" => "Bolivarcoin",
		"BON" => "Bonpay",
		"BOS" => "BOScoin",
		"BOST" => "BoostCoin",
		"BOT" => "Bodhi",
		"BOUTS" => "BoutsPro",
		"BOX" => "ContentBox",
		"BPL" => "Blockpool",
		"BPT" => "Blockport",
		"BQ" => "bitqy",
		"BRAT" => "BROTHER",
		"BRD" => "Bread",
		"BRIA" => "BriaCoin",
		"BRIT" => "BritCoin",
		"BRK" => "Breakout",
		"BRM" => "BrahmaOS",
		"BRO" => "Bitradio",
		"BRX" => "Breakout Stake",
		"BSC" => "BowsCoin",
		"BSD" => "BitSend",
		"BSM" => "Bitsum",
		"BSN" => "Bastonet",
		"BSR" => "BitSoar",
		"BSTN" => "BitStation",
		"BSTY" => "GlobalBoost-Y",
		"BT2" => "BT2 [CST]",
		"BTA" => "Bata",
		"BTB" => "BitBar",
		"BTBc" => "Bitbase",
		"BTC" => "Bitcoin",
		"BTCA" => "Bitair",
		"BTCD" => "BitcoinDark",
		"BTCM" => "BTCMoon",
		"BTCP" => "Bitcoin Private",
		"BTCR" => "Bitcurrency",
		"BTCRED" => "Bitcoin Red",
		"BTCS" => "Bitcoin Scrypt",
		"BTCZ" => "BitcoinZ",
		"BTDX" => "Bitcloud",
		"BTE" => "BitSerial",
		"BTG" => "Bitcoin Gold",
		"BTM" => "Bytom",
		"BTO" => "Bottos",
		"BTPL" => "Bitcoin Planet",
		"BTQ" => "BitQuark",
		"BTRN" => "Biotron",
		"BTS" => "BitShares",
		"BTW" => "BitWhite",
		"BTWTY" => "Bit20",
		"BTX" => "Bitcore",
		"BUB" => "Bubble",
		"BUBO" => "Budbo",
		"BUMBA" => "BumbaCoin",
		"BUN" => "BunnyCoin",
		"BURST" => "Burst",
		"BUZZ" => "BuzzCoin",
		"BWK" => "Bulwark",
		"BWT" => "Bittwatt",
		"BWX" => "Blue Whale Token",
		"BYC" => "Bytecent",
		"BZ" => "Bit-Z Token",
		"BZNT" => "Bezant",
		"C2" => "Coin2.1",
		"C20" => "CRYPTO20",
		"CAB" => "Cabbage",
		"CACH" => "CacheCoin",
		"CAG" => "Change",
		"CAN" => "CanYaCoin",
		"CANDY" => "Candy",
		"CANN" => "CannabisCoin",
		"CAPP" => "Cappasity",
		"CAR" => "CarBlock",
		"CARBON" => "Carboncoin",
		"CARD" => "Cardstack",
		"CAS" => "Cashaa",
		"CASH" => "Cashcoin",
		"CAT" => "BitClave",
		"CAZ" => "Cazcoin",
		"CBC" => "CashBet Coin",
		"CBT" => "CommerceBlock",
		"CBX" => "Bullion",
		"CCCX" => "Clipper Coin",
		"CCN" => "CannaCoin",
		"CCO" => "Ccore",
		"CCRB" => "CryptoCarbon",
		"CCT" => "Crystal Clear ",
		"CDN" => "Canada eCoin",
		"CDT" => "Blox",
		"CDX" => "Commodity Ad Network",
		"CEEK" => "CEEK VR",
		"CEFS" => "CryptopiaFeeShares",
		"CENNZ" => "Centrality",
		"CF" => "Californium",
		"CFC" => "CoffeeCoin",
		"CFI" => "Cofound.it",
		"CFUN" => "CFun",
		"CHAN" => "ChanCoin",
		"CHAT" => "ChatCoin",
		"CHC" => "ChainCoin",
		"CHEAP" => "Cheapcoin",
		"CHESS" => "ChessCoin",
		"CHEX" => "CHEX",
		"CHIPS" => "CHIPS",
		"CHP" => "CoinPoker",
		"CHSB" => "SwissBorg",
		"CHX" => "Chainium",
		"CJ" => "Cryptojacks",
		"CJT" => "ConnectJob",
		"CKUSD" => "CK USD",
		"CL" => "Coinlancer",
		"CLAM" => "Clams",
		"CLD" => "Cloud",
		"CLN" => "Colu Local Network",
		"CLO" => "Callisto Network",
		"CLOAK" => "CloakCoin",
		"CLUB" => "ClubCoin",
		"CMCT" => "Crowd Machine",
		"CMPCO" => "CampusCoin",
		"CMS" => "COMSA [ETH]",
		"CMT" => "CyberMiles",
		"CND" => "Cindicator",
		"CNET" => "ContractNet",
		"CNN" => "Content Neutrality Network",
		"CNNC" => "Cannation",
		"CNO" => "Coin(O)",
		"CNT" => "Centurion",
		"CNX" => "Cryptonex",
		"COAL" => "BitCoal",
		"COB" => "Cobinhood",
		"COFI" => "CoinFi",
		"COLX" => "ColossusXT",
		"CON" => "PayCon",
		"CONI" => "Coni",
		"CONX" => "Concoin",
		"COR" => "CORION",
		"COSM" => "Cosmo Coin",
		"COSS" => "COSS",
		"COU" => "Couchain",
		"COUPE" => "Coupecoin",
		"COV" => "Covesting",
		"COVAL" => "Circuits of Value",
		"CPAY" => "Cryptopay",
		"CPC" => "CPChain",
		"CPN" => "CompuCoin",
		"CPT" => "Cryptaur",
		"CPX" => "Apex",
		"CPY" => "COPYTRACK",
		"CRAVE" => "Crave",
		"CRB" => "Creditbit",
		"CRC" => "CryCash",
		"CRDNC" => "Credence Coin",
		"CRE" => "Cybereits",
		"CREA" => "Creativecoin",
		"CRED" => "Verify",
		"CREDO" => "Credo",
		"CREVA" => "CrevaCoin",
		"CRM" => "Cream",
		"CROP" => "Cropcoin",
		"CRPT" => "Crypterium",
		"CRW" => "Crown",
		"CRYPT" => "CryptCoin",
		"CS" => "Credits",
		"CSC" => "CasinoCoin",
		"CSNO" => "BitDice",
		"CTIC2" => "Coimatic 2.0",
		"CTIC3" => "Coimatic 3.0",
		"CTO" => "Crypto",
		"CTX" => "CarTaxi Token",
		"CTXC" => "Cortex",
		"CUBE" => "DigiCube",
		"CURE" => "Curecoin",
		"CV" => "carVertical",
		"CVC" => "Civic",
		"CVCOIN" => "CVCoin",
		"CVH" => "Curriculum Vitae",
		"CVT" => "CyberVein",
		"CXO" => "CargoX",
		"CXT" => "Coinonat",
		"CYDER" => "Cyder",
		"DADI" => "DADI",
		"DAG" => "Constellation",
		"DAI" => "Dai",
		"DALC" => "Dalecoin",
		"DAN" => "Daneel",
		"DAR" => "Darcrus",
		"DASC" => "DasCoin",
		"DASH" => "Dash",
		"DAT" => "Datum",
		"DATA" => "Streamr DATAcoin",
		"DATX" => "DATx",
		"DAX" => "DAEX",
		"DAXX" => "DaxxCoin",
		"DAY" => "Chronologic",
		"DBC" => "DeepBrain Chain",
		"DBET" => "DecentBet",
		"DBIX" => "DubaiCoin",
		"DBTC" => "Debitcoin",
		"DCC" => "Distributed Credit Chain",
		"DCN" => "Dentacoin",
		"DCR" => "Decred",
		"DCT" => "DECENT",
		"DCY" => "Dinastycoin",
		"DDD" => "Scry.info",
		"DDF" => "DigitalDevelopersFund",
		"DEB" => "Debitum",
		"DEM" => "Deutsche eMark",
		"DENT" => "Dent",
		"DERO" => "Dero",
		"DEUS" => "DeusCoin",
		"DEV" => "DeviantCoin",
		"DEW" => "DEW",
		"DFT" => "DraftCoin",
		"DGB" => "DigiByte",
		"DGC" => "Digitalcoin",
		"DGD" => "DigixDAO",
		"DGPT" => "DigiPulse",
		"DGTX" => "Digitex Futures",
		"DGX" => "Digix Gold Token",
		"DICE" => "Etheroll",
		"DIG" => "Dignity",
		"DIM" => "DIMCOIN",
		"DIME" => "Dimecoin",
		"DIVX" => "Divi",
		"DIX" => "Dix Asset",
		"DLC" => "Dollarcoin",
		"DLT" => "Agrello",
		"DMB" => "Digital Money Bits",
		"DMC" => "DynamicCoin",
		"DMD" => "Diamond",
		"DML" => "Decentralized Machine Learning",
		"DMT" => "DMarket",
		"DNA" => "EncrypGen",
		"DNR" => "Denarius",
		"DNT" => "district0x",
		"DOCK" => "Dock",
		"DOGE" => "Dogecoin",
		"DOLLAR" => "Dollar Online",
		"DON" => "Donationcoin",
		"DOPE" => "DopeCoin",
		"DOR" => "Dorado",
		"DOT" => "Dotcoin",
		"DOVU" => "Dovu",
		"DP" => "DigitalPrice",
		"DPY" => "Delphy",
		"DRG" => "Dragon Coins",
		"DRGN" => "Dragonchain",
		"DRM" => "Dreamcoin",
		"DROP" => "Dropil",
		"DRPU" => "DCORP Utility",
		"DRS" => "Digital Rupees",
		"DRT" => "DomRaider",
		"DRXNE" => "DROXNE",
		"DSH" => "Dashcoin",
		"DSR" => "Desire",
		"DTA" => "DATA",
		"DTB" => "Databits",
		"DTC" => "Datacoin",
		"DTH" => "Dether",
		"DTR" => "Dynamic Trading Rights",
		"DTRC" => "Datarius Credit",
		"DTX" => "DaTa eXchange",
		"DUO" => "ParallelCoin",
		"DUTCH" => "Dutch Coin",
		"DWS" => "DWS",
		"DXT" => "Datawallet",
		"DYN" => "Dynamic",
		"EAG" => "EA Coin",
		"EAGLE" => "EagleCoin",
		"EARTH" => "Earth Token",
		"EBCH" => "EBCH",
		"EBET" => "EthBet",
		"EBST" => "eBoost",
		"EBTC" => "eBitcoin",
		"ECA" => "Electra",
		"ECASH" => "Ethereum Cash",
		"ECC" => "ECC",
		"ECH" => "Etherecash",
		"ECN" => "E-coin",
		"ECO" => "EcoCoin",
		"ECOB" => "Ecobit",
		"EDG" => "Edgeless",
		"EDO" => "Eidoo",
		"EDR" => "Endor Protocol",
		"EDRC" => "EDRCoin",
		"EDT" => "EtherDelta Token",
		"EDU" => "EduCoin",
		"EFL" => "e-Gulden",
		"EFX" => "Effect.AI",
		"EFYT" => "Ergo",
		"EGC" => "EverGreenCoin",
		"EGCC" => "Engine",
		"EGG" => "EggCoin",
		"EGT" => "Egretia",
		"EJOY" => "EJOY",
		"EKO" => "EchoLink",
		"EKT" => "EDUCare",
		"EL" => "Elcoin",
		"ELA" => "Elastos",
		"ELE" => "Elementrem",
		"ELEC" => "Electrify.Asia",
		"ELF" => "aelf",
		"ELITE" => "Ethereum Lite",
		"ELIX" => "Elixir",
		"ELLA" => "Ellaism",
		"ELS" => "Elysium",
		"ELTCOIN" => "ELTCOIN",
		"ELY" => "Elysian",
		"EMB" => "EmberCoin",
		"EMC" => "Emercoin",
		"EMC2" => "Einsteinium",
		"EMD" => "Emerald Crypto",
		"EMPR" => "empowr coin",
		"EMV" => "Ethereum Movie Venture",
		"ENG" => "Enigma",
		"ENGT" => "Engagement Token",
		"ENJ" => "Enjin Coin",
		"ENRG" => "Energycoin",
		"ENT" => "Eternity",
		"EOS" => "EOS",
		"EOSDAC" => "eosDAC",
		"EPC" => "Electronic PK Chain",
		"EPY" => "Emphy",
		"EQL" => "Equal",
		"EQT" => "EquiTrader",
		"ERA" => "ERA",
		"ERC" => "EuropeCoin",
		"ERC20" => "ERC20",
		"ERO" => "Eroscoin",
		"ERY" => "Eryllium",
		"ESC" => "Escroco",
		"ESP" => "Espers",
		"ESS" => "Essentia",
		"ESZ" => "EtherSportz",
		"ETBS" => "Ethbits",
		"ETC" => "Ethereum Classic",
		"ETG" => "Ethereum Gold",
		"ETH" => "Ethereum",
		"ETHD" => "Ethereum Dark",
		"ETHOS" => "Ethos",
		"ETK" => "EnergiToken",
		"ETN" => "Electroneum",
		"ETP" => "Metaverse ETP",
		"ETT" => "EncryptoTel [WAVES]",
		"ETZ" => "Ether Zero",
		"EUC" => "Eurocoin",
		"EVC" => "EventChain",
		"EVE" => "Devery",
		"EVIL" => "Evil Coin",
		"EVN" => "Envion",
		"EVR" => "Everus",
		"EVX" => "Everex",
		"EXC" => "Eximchain",
		"EXCL" => "ExclusiveCoin",
		"EXN" => "ExchangeN",
		"EXP" => "Expanse",
		"EXRN" => "EXRNchain",
		"EXY" => "Experty",
		"EZT" => "EZToken",
		"FACE" => "Faceter",
		"FAIR" => "FairCoin",
		"FANS" => "Fantasy Cash",
		"FAP" => "FAPcoin",
		"FCN" => "Fantomcoin",
		"FCT" => "Factom",
		"FDX" => "FidentiaX",
		"FDZ" => "Friendz",
		"FGC" => "FantasyGold",
		"FID" => "Fidelium",
		"FIL" => "Filecoin [Futures]",
		"FJC" => "FujiCoin",
		"FLASH" => "Flash",
		"FLAX" => "Flaxscript",
		"FLDC" => "FoldingCoin",
		"FLIK" => "FLiK",
		"FLIXX" => "Flixxo",
		"FLO" => "FlorinCoin",
		"FLP" => "FLIP",
		"FLT" => "FlutterCoin",
		"FLUZ" => "Fluz Fluz",
		"FND" => "FundRequest",
		"FOR" => "FORCE",
		"FOTA" => "Fortuna",
		"FOXT" => "Fox Trading",
		"FRC" => "Freicoin",
		"FRD" => "Farad",
		"FREC" => "Freyrchain",
		"FRGC" => "Fargocoin",
		"FRN" => "Francs",
		"FRST" => "FirstCoin",
		"FRV" => "Fitrova",
		"FSBT" => "Forty Seven Bank",
		"FSN" => "Fusion",
		"FST" => "Fastcoin",
		"FT" => "Fabric Token",
		"FTC" => "Feathercoin",
		"FTI" => "FansTime",
		"FTO" => "FuturoCoin",
		"FTX" => "FintruX Network",
		"FUEL" => "Etherparty",
		"FUN" => "FunFair",
		"FUNC" => "FUNCoin",
		"FUNK" => "The Cypherfunks",
		"FUZZ" => "FuzzBalls",
		"FXE" => "FuturXe",
		"FXT" => "FuzeX",
		"FYN" => "FundYourselfNow",
		"FYP" => "FlypMe",
		"GAIN" => "UGAIN",
		"GAM" => "Gambit",
		"GAME" => "GameCredits",
		"GAP" => "Gapcoin",
		"GARD" => "Hashgard",
		"GARY" => "President Johnson",
		"GAS" => "Gas",
		"GAT" => "Gatcoin",
		"GB" => "GoldBlocks",
		"GBC" => "Gold Bits Coin",
		"GBG" => "Golos Gold",
		"GBX" => "GoByte",
		"GBYTE" => "Byteball Bytes",
		"GCC" => "Global Cryptocurrency",
		"GCN" => "GCN Coin",
		"GCR" => "Global Currency Reserve",
		"GCS" => "GameChain System",
		"GDC" => "GrandCoin",
		"GEERT" => "GeertCoin",
		"GEM" => "Gems ",
		"GEN" => "DAOstack",
		"GENE" => "Parkgene",
		"GEO" => "GeoCoin",
		"GET" => "GET Protocol",
		"GETX" => "Guaranteed Ethurance Token Extra",
		"GIN" => "GINcoin",
		"GLA" => "Gladius Token",
		"GLC" => "GlobalCoin",
		"GLD" => "GoldCoin",
		"GLS" => "GlassCoin",
		"GLT" => "GlobalToken",
		"GMT" => "Mercury Protocol",
		"GMX" => "GoldMaxCoin",
		"GNO" => "Gnosis",
		"GNT" => "Golem",
		"GNX" => "Genaro Network",
		"GO" => "GoChain",
		"GOD" => "Bitcoin God",
		"GOLF" => "Golfcoin",
		"GOLOS" => "Golos",
		"GOOD" => "Goodomy",
		"GOT" => "GoNetwork",
		"GP" => "GoldPieces",
		"GPL" => "Gold Pressed Latinum",
		"GRC" => "GridCoin",
		"GRFT" => "Graft",
		"GRID" => "Grid+",
		"GRIM" => "Grimcoin",
		"GRLC" => "Garlicoin",
		"GRMD" => "GreenMed",
		"GRN" => "Granite",
		"GRS" => "Groestlcoin",
		"GRWI" => "Growers International",
		"GRX" => "GOLD Reward Token",
		"GSC" => "Global Social Chain",
		"GSR" => "GeyserCoin",
		"GTC" => "Game.com",
		"GTO" => "Gifto",
		"GUESS" => "Peerguess",
		"GUN" => "Guncoin",
		"GUP" => "Matchpool",
		"GVE" => "Globalvillage Ecosystem",
		"GVT" => "Genesis Vision",
		"GXS" => "GXChain",
		"HAC" => "Hackspace Capital",
		"HAL" => "Halcyon",
		"HALLO" => "Halloween Coin",
		"HAT" => "Hat.Exchange",
		"HAV" => "Havven",
		"HBC" => "HomeBlockCoin",
		"HBN" => "HoboNickels",
		"HBT" => "Hubii Network",
		"HBZ" => "Helbiz",
		"HC" => "Harvest Masternode Coin",
		"HDG" => "Hedge",
		"HDLB" => "HODL Bucks",
		"HEAT" => "HEAT",
		"HER" => "HeroNode",
		"HERO" => "Sovereign Hero",
		"HGT" => "HelloGold",
		"HIGH" => "High Gain",
		"HIRE" => "HireMatch",
		"HKN" => "Hacken",
		"HLC" => "HalalChain",
		"HMC" => "Hi Mutual Society",
		"HMQ" => "Humaniq",
		"HNC" => "Helleniccoin",
		"HODL" => "HOdlcoin",
		"HOLD" => "Stellar Holdings",
		"HONEY" => "Honey",
		"HORSE" => "Ethorse",
		"HOT" => "Holo",
		"HPB" => "High Performance Blockchain",
		"HPC" => "Happycoin",
		"HPY" => "Hyper Pay",
		"HQX" => "HOQU",
		"HSC" => "HashCoin",
		"HSR" => "Hshare",
		"HST" => "Decision Token",
		"HT" => "Huobi Token",
		"HTML" => "HTMLCOIN",
		"HUC" => "HunterCoin",
		"HUR" => "Hurify",
		"HUSH" => "Hush",
		"HVCO" => "High Voltage",
		"HVN" => "Hive Project",
		"HWC" => "HollyWoodCoin",
		"HXX" => "Hexx",
		"HYDRO" => "Hydro",
		"HYP" => "HyperStake",
		"HYPER" => "Hyper",
		"I0C" => "I0Coin",
		"IBANK" => "iBank",
		"IC" => "Ignition",
		"ICN" => "Iconomi",
		"ICOB" => "ICOBID",
		"ICON" => "Iconic",
		"ICOO" => "ICO OpenLedger",
		"ICOS" => "ICOS",
		"ICX" => "ICON",
		"IDH" => "indaHash",
		"IDT" => "InvestDigital",
		"IDXM" => "IDEX Membership",
		"IETH" => "iEthereum",
		"IFC" => "Infinitecoin",
		"IFLT" => "InflationCoin",
		"IFT" => "InvestFeed",
		"IGNIS" => "Ignis",
		"IHT" => "IHT Real Estate Protocol",
		"IIC" => "Intelligent Investment Chain",
		"IMS" => "Independent Money System",
		"IMX" => "Impact",
		"INC" => "Influence Chain",
		"INCNT" => "Incent",
		"IND" => "Indorse Token",
		"INDI" => "Indicoin",
		"INFX" => "Influxcoin",
		"ING" => "Iungo",
		"INK" => "Ink",
		"INN" => "Innova",
		"INPAY" => "InPay",
		"INS" => "INS Ecosystem",
		"INSN" => "InsaneCoin",
		"INSTAR" => "Insights Network",
		"INSUR" => "InsurChain",
		"INT" => "Internet Node Token",
		"INV" => "Invacio",
		"INXT" => "Internxt",
		"IOC" => "I/O Coin",
		"ION" => "ION",
		"IOP" => "Internet of People",
		"IOST" => "IOST",
		"IOTX" => "IoTeX",
		"IPC" => "IPChain",
		"IPL" => "InsurePal",
		"IPSX" => "IP Exchange",
		"IQ" => "Everipedia",
		"IQT" => "iQuant",
		"IRL" => "IrishCoin",
		"ISL" => "IslaCoin",
		"ITC" => "IoT Chain",
		"ITI" => "iTicoin",
		"ITNS" => "IntenseCoin",
		"ITT" => "Intelligent Trading Foundation",
		"ITZ" => "Interzone",
		"IVY" => "Ivy",
		"IXC" => "Ixcoin",
		"IXT" => "IXT",
		"J" => "Joincoin",
		"J8T" => "JET8",
		"JC" => "Jesus Coin",
		"JET" => "Jetcoin",
		"JEW" => "Shekel",
		"JIN" => "Jin Coin",
		"JIYO" => "Jiyo",
		"JNT" => "Jibrel Network",
		"JOBS" => "JobsCoin",
		"JOT" => "Jury.Online Token",
		"JS" => "JavaScript Token",
		"KB3" => "B3Coin",
		"KBC" => "Karatgold Coin",
		"KBR" => "Kubera Coin",
		"KCASH" => "Kcash",
		"KCS" => "KuCoin Shares",
		"KDC" => "KlondikeCoin",
		"KED" => "Darsek",
		"KEK" => "KekCoin",
		"KEY" => "Selfkey",
		"KICK" => "KickCoin",
		"KIN" => "Kin",
		"KLC" => "KiloCoin",
		"KLN" => "Kolion",
		"KMD" => "Komodo",
		"KNC" => "Kyber Network",
		"KNDC" => "KanadeCoin",
		"KOBO" => "Kobocoin",
		"KORE" => "Kore",
		"KRB" => "Karbo",
		"KRL" => "Kryll",
		"KRM" => "Karma",
		"KRONE" => "Kronecoin",
		"KST" => "StarCoin",
		"KURT" => "Kurrent",
		"KUSH" => "KushCoin",
		"LA" => "LATOKEN",
		"LALA" => "LALA World",
		"LANA" => "LanaCoin",
		"LATX" => "LatiumX",
		"LBA" => "Libra Credit",
		"LBC" => "LBRY Credits",
		"LBTC" => "LiteBitcoin",
		"LCC" => "Litecoin Cash",
		"LCP" => "Litecoin Plus",
		"LCS" => "Local Coin Swap",
		"LDC" => "Leadcoin",
		"LDCN" => "LandCoin",
		"LDOGE" => "LiteDoge",
		"LEA" => "LeaCoin",
		"LEDU" => "Education Ecosystem",
		"LEMO" => "LemoChain",
		"LEND" => "ETHLend",
		"LEO" => "LEOcoin",
		"LET" => "LinkEye",
		"LEV" => "Leverj",
		"LEVO" => "Levocoin",
		"LGO" => "LGO Exchange",
		"LIF" => "Winding Tree",
		"LIFE" => "LIFE",
		"LIGHT" => "LightChain",
		"LIKE" => "LikeCoin",
		"LINDA" => "Linda",
		"LINK" => "ChainLink",
		"LINX" => "Linx",
		"LIR" => "LetItRide",
		"LIVE" => "Live Stars",
		"LKK" => "Lykke",
		"LMC" => "LoMoCoin",
		"LNC" => "Linker Coin",
		"LND" => "Lendingblock",
		"LOC" => "LockTrip",
		"LOCI" => "LOCIcoin",
		"LOG" => "Woodcoin",
		"LOKI" => "Loki",
		"LOOM" => "Loom Network",
		"LPC" => "Lightpaycoin",
		"LRC" => "Loopring",
		"LRN" => "Loopring [NEO]",
		"LSK" => "Lisk",
		"LST" => "Lendroid Support Token",
		"LTB" => "LiteBar",
		"LTC" => "Litecoin",
		"LTCR" => "Litecred",
		"LTCU" => "LiteCoin Ultra",
		"LUC" => "Level Up Coin",
		"LUN" => "Lunyr",
		"LUNA" => "Luna Coin",
		"LUX" => "LUXCoin",
		"LVPS" => "LevoPlus",
		"LWF" => "Local World Forwarders",
		"LYL" => "LoyalCoin",
		"LYM" => "Lympo",
		"MAC" => "Machinecoin",
		"MAG" => "Magnet",
		"MAGE" => "MagicCoin",
		"MAGN" => "Magnetcoin",
		"MAID" => "MaidSafeCoin",
		"MAN" => "Matrix AI Network",
		"MANA" => "Decentraland",
		"MANNA" => "Manna",
		"MAO" => "Mao Zedong",
		"MAR" => "Marijuanacoin",
		"MARS" => "Marscoin",
		"MARX" => "MarxCoin",
		"MAX" => "MaxCoin",
		"MAY" => "Theresa May Coin",
		"MAZA" => "MAZA",
		"MBI" => "Monster Byte",
		"MBRS" => "Embers",
		"MCAP" => "MCAP",
		"MCI" => "Musiconomi",
		"MCO" => "MCO",
		"MCRN" => "MACRON",
		"MDA" => "Moeda Loyalty Points",
		"MDS" => "MediShares",
		"MDT" => "Measurable Data Token",
		"MEC" => "Megacoin",
		"MED" => "MediBloc [QRC20]",
		"MEDIC" => "MedicCoin",
		"MEDX" => "MediBloc [ERC20]",
		"MEET" => "CoinMeet",
		"MEME" => "Memetic / PepeCoin",
		"MER" => "Mercury",
		"MET" => "Metronome",
		"METAL" => "MetalCoin",
		"MFG" => "SyncFab",
		"MFT" => "Mainframe",
		"MGM" => "Magnum",
		"MGO" => "MobileGo",
		"MILO" => "MiloCoin",
		"MINEX" => "Minex",
		"MINT" => "Mintcoin",
		"MIOTA" => "IOTA",
		"MITH" => "Mithril",
		"MITX" => "Morpheus Labs",
		"MKR" => "Maker",
		"MLM" => "MktCoin",
		"MLN" => "Melon",
		"MNC" => "Mincoin",
		"MNE" => "Minereum",
		"MNM" => "Mineum",
		"MNTP" => "GoldMint",
		"MNX" => "MinexCoin",
		"MOAC" => "MOAC",
		"MOBI" => "Mobius",
		"MOC" => "Mossland",
		"MOD" => "Modum",
		"MOF" => "Molecular Future",
		"MOIN" => "Moin",
		"MOJO" => "MojoCoin",
		"MONA" => "MonaCoin",
		"MONK" => "Monkey Project",
		"MOON" => "Mooncoin",
		"MORE" => "More Coin",
		"MORPH" => "Morpheus Network",
		"MOT" => "Olympus Labs",
		"MOTO" => "Motocoin",
		"MRK" => "MARK.SPACE",
		"MRQ" => "MIRQ",
		"MRT" => "Miners' Reward Token",
		"MSCN" => "Master Swiscoin",
		"MSD" => "MSD",
		"MSP" => "Mothership",
		"MSR" => "Masari",
		"MST" => "MustangCoin",
		"MT" => "MyToken",
		"MTC" => "Docademic",
		"MTH" => "Monetha",
		"MTL" => "Metal",
		"MTN" => "Medicalchain",
		"MTNC" => "Masternodecoin",
		"MTX" => "Matryx",
		"MUE" => "MonetaryUnit",
		"MUSE" => "MUSE",
		"MUSIC" => "Musicoin",
		"MVC" => "Maverick Chain",
		"MVP" => "Merculet",
		"MWAT" => "Restart Energy MWAT",
		"MXT" => "MarteXcoin",
		"MYB" => "MyBit Token",
		"MYST" => "Mysterium",
		"NAMO" => "NamoCoin",
		"NANJ" => "NANJCOIN",
		"NANO" => "Nano",
		"NANOX" => "Project-X",
		"NAS" => "Nebulas",
		"NAV" => "NavCoin",
		"NAVI" => "Naviaddress",
		"NBAI" => "Nebula AI",
		"NCASH" => "Nucleus Vision",
		"NCT" => "PolySwarm",
		"NDC" => "NEVERDIE",
		"NEBL" => "Neblio",
		"NEC" => "Nectar",
		"NEO" => "NEO",
		"NEOG" => "NEO GOLD",
		"NEOS" => "NeosCoin",
		"NET" => "Nimiq Exchange Token",
		"NETKO" => "Netko",
		"NEU" => "Neumark",
		"NEVA" => "NevaCoin",
		"NEXO" => "Nexo",
		"NGC" => "NAGA",
		"NIO" => "Autonio",
		"NKA" => "IncaKoin",
		"NKC" => "Nework",
		"NKN" => "NKN",
		"NLC2" => "NoLimitCoin",
		"NLG" => "Gulden",
		"NLX" => "Nullex",
		"NMC" => "Namecoin",
		"NMR" => "Numeraire",
		"NMS" => "Numus",
		"NOAH" => "Noah Coin",
		"NOBL" => "NobleCoin",
		"NOBS" => "No BS Crypto",
		"NOTE" => "DNotes",
		"NOX" => "Nitro",
		"NPER" => "NPER",
		"NPX" => "NaPoleonX",
		"NPXS" => "Pundi X",
		"NRO" => "Neuro",
		"NRVE" => "Narrative",
		"NSR" => "NuShares",
		"NTK" => "Neurotoken",
		"NTO" => "Fujinto",
		"NTRN" => "Neutron",
		"NTWK" => "Network Token",
		"NTY" => "Nexty",
		"NUKO" => "Nekonium",
		"NULS" => "Nuls",
		"NUMUS" => "NumusCash",
		"NUSD" => "nUSD",
		"NVC" => "Novacoin",
		"NXC" => "Nexium",
		"NXS" => "Nexus",
		"NXT" => "Nxt",
		"NYAN" => "Nyancoin",
		"NYC" => "NewYorkCoin",
		"OAX" => "OAX",
		"OBITS" => "OBITS",
		"OC" => "OceanChain",
		"OCC" => "Octoin Coin",
		"OCL" => "Oceanlab",
		"OCN" => "Odyssey",
		"OCT" => "OracleChain",
		"ODE" => "ODEM",
		"ODN" => "Obsidian",
		"OF" => "OFCOIN",
		"OK" => "OKCash",
		"OLE" => "Olive",
		"OLT" => "OneLedger",
		"OMC" => "Omicron",
		"OMG" => "OmiseGO",
		"OMNI" => "Omni",
		"OMX" => "Shivom",
		"ONG" => "onG.social",
		"ONION" => "DeepOnion",
		"ONL" => "On.Live",
		"ONT" => "Ontology",
		"ONX" => "Onix",
		"OOT" => "Utrum",
		"OPAL" => "Opal",
		"OPC" => "OP Coin",
		"OPEN" => "Open Platform",
		"OPT" => "Opus",
		"ORB" => "Orbitcoin",
		"ORE" => "Galactrum",
		"ORI" => "Origami",
		"ORME" => "Ormeus Coin",
		"ORS" => "Origin Sport",
		"OST" => "OST",
		"OTB" => "OTCBTC Token",
		"OTN" => "Open Trading Network",
		"OTX" => "Octanox",
		"OXY" => "Oxycoin",
		"PAI" => "PCHAIN",
		"PAK" => "Pakcoin",
		"PAL" => "PolicyPal Network",
		"PARETO" => "Pareto Network",
		"PART" => "Particl",
		"PASC" => "Pascal Coin",
		"PASL" => "Pascal Lite",
		"PAT" => "Patron",
		"PAY" => "TenX",
		"PAYX" => "Paypex",
		"PBL" => "Publica",
		"PBT" => "Primalbase Token",
		"PCH" => "POPCHAIN",
		"PCL" => "Peculium",
		"PCN" => "PeepCoin",
		"PCOIN" => "Pioneer Coin",
		"PCS" => "Pabyosi Coin (Special)",
		"PEPECASH" => "Pepe Cash",
		"PEX" => "PosEx",
		"PFR" => "Payfair",
		"PHI" => "PHI Token",
		"PHO" => "Photon",
		"PHR" => "Phore",
		"PHS" => "Philosopher Stones",
		"PIE" => "PIECoin",
		"PIGGY" => "Piggycoin",
		"PING" => "CryptoPing",
		"PINK" => "PinkCoin",
		"PIPL" => "PiplCoin",
		"PIRL" => "Pirl",
		"PIVX" => "PIVX",
		"PIX" => "Lampix",
		"PKB" => "ParkByte",
		"PKC" => "PikcioChain",
		"PKT" => "Playkey",
		"PLACO" => "PlayerCoin",
		"PLAN" => "Plancoin",
		"PLAY" => "HEROcoin",
		"PLBT" => "Polybius",
		"PLC" => "Polcoin",
		"PLNC" => "PLNcoin",
		"PLR" => "Pillar",
		"PLU" => "Pluton",
		"PLX" => "PlexCoin",
		"PLY" => "PlayCoin",
		"PMNT" => "Paymon",
		"PND" => "Pandacoin",
		"PNT" => "Penta",
		"PNX" => "Phantomx",
		"POA" => "POA Network",
		"POE" => "Po.et",
		"POLIS" => "Polis",
		"POLL" => "ClearPoll",
		"POLY" => "Polymath",
		"PONZI" => "PonziCoin",
		"POP" => "PopularCoin",
		"POS" => "PoSToken",
		"POST" => "PostCoin",
		"POSW" => "PoSW Coin",
		"POT" => "PotCoin",
		"POWR" => "Power Ledger",
		"PPC" => "Peercoin",
		"PPP" => "PayPie",
		"PPT" => "Populous",
		"PPY" => "Peerplays",
		"PR" => "Prototanium",
		"PRA" => "ProChain",
		"PRC" => "PRCoin",
		"PRE" => "Presearch",
		"PRES" => "President Trump",
		"PRG" => "Paragon",
		"PRIX" => "Privatix",
		"PRL" => "Oyster",
		"PRM" => "PrismChain",
		"PRN" => "Protean",
		"PRO" => "Propy",
		"PROC" => "ProCurrency",
		"PROUD" => "PROUD Money",
		"PRS" => "PressOne",
		"PST" => "Primas",
		"PTC" => "Pesetacoin",
		"PTOY" => "Patientory",
		"PTT" => "Proton Token",
		"PURA" => "Pura",
		"PURE" => "Pure",
		"PUT" => "Profile Utility Token",
		"PWR" => "Powercoin",
		"PXC" => "Phoenixcoin",
		"PXI" => "Prime-XI",
		"PYLNT" => "Pylon Network",
		"PZM" => "PRIZM",
		"Q2C" => "QubitCoin",
		"QASH" => "QASH",
		"QAU" => "Quantum",
		"QBC" => "Quebecoin",
		"QBIC" => "Qbic",
		"QBT" => "Qbao",
		"QCN" => "QuazarCoin",
		"QKC" => "QuarkChain",
		"QLC" => "QLINK",
		"QRK" => "Quark",
		"QRL" => "Quantum Resistant Ledger",
		"QSP" => "Quantstamp",
		"QTL" => "Quatloo",
		"QTUM" => "Qtum",
		"QUBE" => "Qube",
		"QUN" => "QunQun",
		"QVT" => "Qvolta",
		"QWARK" => "Qwark",
		"R" => "Revain",
		"RADS" => "Radium",
		"RAIN" => "Condensate",
		"RBBT" => "RabbitCoin",
		"RBIES" => "Rubies",
		"RBLX" => "Rublix",
		"RBT" => "Rimbit",
		"RBY" => "Rubycoin",
		"RC" => "RussiaCoin",
		"RCD" => "RECORD",
		"RCN" => "Ripio Credit Network",
		"RCT" => "RealChain",
		"RDD" => "ReddCoin",
		"RDN" => "Raiden Network Token",
		"READ" => "Read",
		"REAL" => "REAL",
		"REBL" => "REBL",
		"REC" => "Regalcoin",
		"RED" => "RED",
		"REF" => "RefToken",
		"REGA" => "Regacoin",
		"REM" => "Remme",
		"REN" => "Republic Protocol",
		"REP" => "Augur",
		"REPO" => "REPO",
		"REQ" => "Request Network",
		"REX" => "imbrex",
		"RFR" => "Refereum",
		"RHOC" => "RChain",
		"RIC" => "Riecoin",
		"RICHX" => "RichCoin",
		"RISE" => "Rise",
		"RIYA" => "Etheriya",
		"RKC" => "Royal Kingdom Coin",
		"RKT" => "Rock",
		"RLC" => "iExec RLC",
		"RLT" => "RouletteToken",
		"RLX" => "Relex",
		"RMC" => "Russian Miner Coin",
		"RMT" => "SureRemit",
		"RNS" => "Renos",
		"RNT" => "OneRoot Network",
		"RNTB" => "BitRent",
		"ROOFS" => "Roofs",
		"RPC" => "RonPaulCoin",
		"RPL" => "Rocket Pool",
		"RPX" => "Red Pulse",
		"RTB" => "AB-Chain RTB",
		"RTE" => "Rate3",
		"RUFF" => "Ruff",
		"RUNNERS" => "Runners",
		"RUP" => "Rupee",
		"RUPX" => "Rupaya",
		"RVN" => "Ravencoin",
		"RVR" => "RevolutionVR",
		"RVT" => "Rivetz",
		"SAFEX" => "Safe Exchange Coin",
		"SAGA" => "SagaCoin",
		"SAK" => "Sharkcoin",
		"SAL" => "SalPay",
		"SALT" => "SALT",
		"SAN" => "Santiment Network Token",
		"SANDG" => "Save and Gain",
		"SBC" => "StrikeBitClub",
		"SBD" => "Steem Dollars",
		"SBTC" => "Super Bitcoin",
		"SC" => "Siacoin",
		"SCC" => "StockChain",
		"SCL" => "Sociall",
		"SCRL" => "Scroll",
		"SCRT" => "SecretCoin",
		"SCS" => "SpeedCash",
		"SCT" => "Soma",
		"SDRN" => "Senderon",
		"SEELE" => "Seele",
		"SEER" => "SEER",
		"SEN" => "Consensus",
		"SENC" => "Sentinel Chain",
		"SEND" => "Social Send",
		"SENSE" => "Sense",
		"SENT" => "Sentinel",
		"SEQ" => "Sequence",
		"SETH" => "Sether",
		"SEXC" => "ShareX",
		"SFC" => "Solarflarecoin",
		"SFU" => "Saifu",
		"SGCC" => "Super Game Chain",
		"SGN" => "Signals Network",
		"SGR" => "Sugar Exchange",
		"SHA" => "SHACoin",
		"SHDW" => "Shadow Token",
		"SHELL" => "ShellCoin",
		"SHIFT" => "Shift",
		"SHIP" => "ShipChain",
		"SHL" => "Oyster Shell",
		"SHND" => "StrongHands",
		"SHOP" => "Shopin",
		"SHOW" => "Show",
		"SHP" => "Sharpe Platform Token",
		"SIB" => "SIBCoin",
		"SIC" => "Swisscoin",
		"SIG" => "Spectiv",
		"SIGMA" => "SIGMAcoin",
		"SIGT" => "Signatum",
		"SISA" => "SISA",
		"SJCX" => "Storjcoin X",
		"SJW" => "SJWCoin",
		"SKB" => "Sakura Bloom",
		"SKC" => "Skeincoin",
		"SKIN" => "SkinCoin",
		"SKM" => "Skrumble Network",
		"SKR" => "Sakuracoin",
		"SKY" => "Skycoin",
		"SLEVIN" => "Slevin",
		"SLG" => "Sterlingcoin",
		"SLOTH" => "Slothcoin",
		"SLR" => "SolarCoin",
		"SLS" => "SaluS",
		"SLT" => "Smartlands",
		"SMART" => "SmartCash",
		"SMC" => "SmartCoin",
		"SMLY" => "SmileyCoin",
		"SMOKE" => "Smoke",
		"SMS" => "Speed Mining Service",
		"SMT" => "SmartMesh",
		"SNC" => "SunContract",
		"SNGLS" => "SingularDTV",
		"SNIP" => "SnipCoin",
		"SNM" => "SONM",
		"SNOV" => "Snovio",
		"SNRG" => "Synergy",
		"SNT" => "Status",
		"SNTR" => "Silent Notary",
		"SOAR" => "Soarcoin",
		"SOC" => "All Sports",
		"SOCC" => "SocialCoin",
		"SOIL" => "SOILcoin",
		"SONG" => "SongCoin",
		"SOON" => "SoonCoin",
		"SOP" => "SoPay",
		"SOUL" => "Phantasma",
		"SPACE" => "SpaceCoin",
		"SPANK" => "SpankChain",
		"SPC" => "SpaceChain",
		"SPD" => "Stipend",
		"SPF" => "SportyCo",
		"SPHR" => "Sphere",
		"SPHTX" => "SophiaTX",
		"SPK" => "Sparks",
		"SPR" => "SpreadCoin",
		"SPRTS" => "Sprouts",
		"SPX" => "Sp8de",
		"SRC" => "SecureCoin",
		"SRCOIN" => "SRCOIN",
		"SRN" => "SIRIN LABS Token",
		"SS" => "Sharder",
		"SSC" => "SelfSell",
		"SSP" => "Smartshare",
		"SSS" => "Sharechain",
		"STA" => "Starta",
		"STAC" => "StarterCoin",
		"STAK" => "STRAKS",
		"STAR" => "Starbase",
		"STARS" => "StarCash Network",
		"START" => "Startcoin",
		"STC" => "StarChain",
		"STEEM" => "Steem",
		"STEX" => "STEX",
		"STK" => "STK",
		"STN" => "Steneum Coin",
		"STORJ" => "Storj",
		"STORM" => "Storm",
		"STQ" => "Storiqa",
		"STRAT" => "Stratis",
		"STRC" => "StarCredits",
		"STU" => "bitJob",
		"STV" => "Sativacoin",
		"STX" => "Stox",
		"SUB" => "Substratum",
		"SUMO" => "Sumokoin",
		"SUP" => "Superior Coin",
		"SUPER" => "SuperCoin",
		"SUR" => "Suretly",
		"SWFTC" => "SwftCoin",
		"SWIFT" => "Bitswift",
		"SWING" => "Swing",
		"SWM" => "Swarm",
		"SWT" => "Swarm City",
		"SWTC" => "Jingtum Tech",
		"SWTH" => "Switcheo",
		"SXC" => "Sexcoin",
		"SXDT" => "Spectre.ai Dividend Token",
		"SXUT" => "Spectre.ai Utility Token",
		"SYNX" => "Syndicate",
		"SYS" => "Syscoin",
		"TAAS" => "TaaS",
		"TAG" => "TagCoin",
		"TAJ" => "TajCoin",
		"TALK" => "BTCtalkcoin",
		"TAU" => "Lamden",
		"TBX" => "Tokenbox",
		"TCC" => "The ChampCoin",
		"TCOIN" => "T-coin",
		"TCT" => "TokenClub",
		"TDS" => "TokenDesk",
		"TDX" => "Tidex Token",
		"TEAM" => "TEAM (TokenStars)",
		"TEK" => "TEKcoin",
		"TEL" => "Telcoin",
		"TELL" => "Tellurion",
		"TEN" => "Tokenomy",
		"TER" => "TerraNova",
		"TERN" => "Ternio",
		"TES" => "TeslaCoin",
		"TESLA" => "TeslaCoilCoin",
		"TFD" => "TE-FOOD",
		"TFL" => "TrueFlip",
		"TGAME" => "Truegame",
		"TGC" => "Tigercoin",
		"TGT" => "Target Coin",
		"THC" => "HempCoin",
		"THETA" => "Theta Token",
		"THRT" => "Thrive Token",
		"TIE" => "Ties.DB",
		"TIG" => "Tigereum",
		"TIME" => "Chronobank",
		"TIO" => "Trade Token",
		"TIPS" => "FedoraCoin",
		"TIT" => "Titcoin",
		"TIX" => "Blocktix",
		"TKA" => "Tokia",
		"TKN" => "TokenCard",
		"TKR" => "CryptoInsight",
		"TKS" => "Tokes",
		"TKY" => "THEKEY",
		"TLE" => "Tattoocoin (Limited Edition)",
		"TMT" => "TRAXIA",
		"TNB" => "Time New Bank",
		"TNC" => "Trinity Network Credit",
		"TNS" => "Transcodium",
		"TNT" => "Tierion",
		"TOA" => "ToaCoin",
		"TOK" => "Tokugawa",
		"TOKC" => "TOKYO",
		"TOLL" => "Bridge Protocol",
		"TOMO" => "TomoChain",
		"TOP" => "TopCoin",
		"TOPC" => "TopChain",
		"TOTO" => "Tourist Token",
		"TPAY" => "TokenPay",
		"TRAC" => "OriginTrail",
		"TRAK" => "TrakInvest",
		"TRC" => "Terracoin",
		"TRCT" => "Tracto",
		"TRDT" => "Trident Group",
		"TRF" => "Travelflex",
		"TRI" => "Triangles",
		"TRIG" => "Triggers",
		"TRIO" => "Tripio",
		"TRK" => "Truckcoin",
		"TROLL" => "Trollcoin",
		"TRST" => "WeTrust",
		"TRTL" => "Turtlecoin",
		"TRTT" => "Trittium",
		"TRUE" => "True Chain",
		"TRUMP" => "TrumpCoin",
		"TRUST" => "TrustPlus",
		"TRX" => "TRON",
		"TSE" => "Tattoocoin (Standard Edition)",
		"TSL" => "Energo",
		"TSTR" => "Tristar Coin",
		"TTC" => "TittieCoin",
		"TTT" => "TrustNote",
		"TTU" => "TaTaTu",
		"TUBE" => "BitTube",
		"TURBO" => "TurboCoin",
		"TUSD" => "TrueUSD",
		"TX" => "TransferCoin",
		"TZC" => "TrezarCoin",
		"UBQ" => "Ubiq",
		"UBT" => "Unibright",
		"UBTC" => "United Bitcoin",
		"UCASH" => "U.CASH",
		"UCOM" => "United Crypto Community",
		"UET" => "Useless Ethereum Token",
		"UFO" => "Uniform Fiscal Object",
		"UFR" => "Upfiring",
		"UGC" => "ugChain",
		"UIP" => "UnlimitedIP",
		"UIS" => "Unitus",
		"UKG" => "Unikoin Gold",
		"ULA" => "Ulatech",
		"UNB" => "UnbreakableCoin",
		"UNI" => "Universe",
		"UNIC" => "UniCoin",
		"UNIFY" => "Unify",
		"UNIT" => "Universal Currency",
		"UNITY" => "SuperNET",
		"UNO" => "Unobtanium",
		"UNRC" => "UniversalRoyalCoin",
		"UP" => "UpToken",
		"UPP" => "Sentinel Protocol",
		"UQC" => "Uquid Coin",
		"UR" => "UR",
		"USC" => "Ultimate Secure Cash",
		"USDT" => "Tether",
		"USNBT" => "NuBits",
		"UTC" => "UltraCoin",
		"UTK" => "UTRUST",
		"UTNP" => "Universa",
		"UTT" => "United Traders Token",
		"UUU" => "U Network",
		"V" => "Version",
		"VCT" => "ValueCyberToken",
		"VEC2" => "VectorAI",
		"VEE" => "BLOCKv",
		"VEN" => "VeChain",
		"VERI" => "Veritaseum",
		"VIA" => "Viacoin",
		"VIB" => "Viberate",
		"VIBE" => "VIBE",
		"VIDZ" => "PureVidz",
		"VIEW" => "View",
		"VIKKY" => "VikkyToken",
		"VIPS" => "Vipstar Coin",
		"VISIO" => "Visio",
		"VIT" => "Vice Industry Token",
		"VITE" => "VITE",
		"VIU" => "Viuly",
		"VIVO" => "VIVO",
		"VLC" => "ValueChain",
		"VLT" => "Veltor",
		"VLTC" => "Vault Coin",
		"VME" => "VeriME",
		"VOISE" => "Voise",
		"VOLT" => "Bitvolt",
		"VOT" => "VoteCoin",
		"VPRC" => "VapersCoin",
		"VRC" => "VeriCoin",
		"VRM" => "VeriumReserve",
		"VRS" => "Veros",
		"VSL" => "vSlice",
		"VSX" => "Vsync",
		"VTA" => "Virtacoin",
		"VTC" => "Vertcoin",
		"VTR" => "vTorrent",
		"VUC" => "Virta Unique Coin",
		"VULC" => "Vulcano",
		"VZT" => "Vezt",
		"W3C" => "W3Coin",
		"WA" => "WA Space",
		"WABI" => "WaBi",
		"WAN" => "Wanchain",
		"WAND" => "WandX",
		"WAVES" => "Waves",
		"WAX" => "WAX",
		"WBB" => "Wild Beast Block",
		"WC" => "WINCOIN",
		"WCT" => "Waves Community Token",
		"WDC" => "WorldCoin",
		"WETH" => "WETH",
		"WGO" => "WavesGo",
		"WGR" => "Wagerr",
		"WHL" => "WhaleCoin",
		"WIC" => "Wi Coin",
		"WICC" => "WaykiChain",
		"WILD" => "Wild Crypto",
		"WIN" => "WCOIN",
		"WINGS" => "Wings",
		"WINK" => "Wink",
		"WISH" => "MyWish",
		"WOMEN" => "WomenCoin",
		"WORM" => "HealthyWormCoin",
		"WPR" => "WePower",
		"WRC" => "Worldcore",
		"WSX" => "WeAreSatoshi",
		"WT" => "WeToken",
		"WTC" => "Waltonchain",
		"WWB" => "Wowbit",
		"WYS" => "wys Token",
		"XAS" => "Asch",
		"XAUR" => "Xaurum",
		"XBC" => "Bitcoin Plus",
		"XBL" => "Billionaire Token",
		"XBP" => "BlitzPredict",
		"XBTC21" => "Bitcoin 21",
		"XBTS" => "Beatcoin",
		"XBY" => "XTRABYTES",
		"XCN" => "Cryptonite",
		"XCO" => "X-Coin",
		"XCP" => "Counterparty",
		"XCRE" => "Creatio",
		"XCT" => "C-Bit",
		"XCXT" => "CoinonatX",
		"XDCE" => "XinFin Network",
		"XDN" => "DigitalNote",
		"XEL" => "Elastic",
		"XEM" => "NEM",
		"XES" => "Proxeus",
		"XGOX" => "XGOX",
		"XHI" => "HiCoin",
		"XHV" => "Haven Protocol",
		"XID" => "Sphre AIR ",
		"XIN" => "Mixin",
		"XJO" => "Joulecoin",
		"XLC" => "Leviar",
		"XLM" => "Stellar",
		"XLR" => "Solaris",
		"XMC" => "Monero Classic",
		"XMCC" => "Monoeci",
		"XMCT" => "XMCT",
		"XMG" => "Magi",
		"XMO" => "Monero Original",
		"XMR" => "Monero",
		"XMX" => "XMax",
		"XMY" => "Myriad",
		"XNK" => "Ink Protocol",
		"XNN" => "Xenon",
		"XOT" => "Internet of Things",
		"XP" => "Experience Points",
		"XPA" => "XPA",
		"XPD" => "PetroDollar",
		"XPM" => "Primecoin",
		"XPTX" => "PlatinumBAR",
		"XPY" => "PayCoin",
		"XQN" => "Quotient",
		"XRA" => "Ratecoin",
		"XRC" => "Rawcoin",
		"XRE" => "RevolverCoin",
		"XRH" => "Rhenium",
		"XRL" => "Rialto",
		"XRP" => "XRP",
		"XRY" => "Royalties",
		"XSG" => "SnowGem",
		"XSH" => "SHIELD",
		"XSN" => "Stakenet",
		"XSPEC" => "Spectrecoin",
		"XST" => "Stealth",
		"XSTC" => "Safe Trade Coin",
		"XTD" => "XTD Coin",
		"XTL" => "Stellite",
		"XTO" => "Tao",
		"XTZ" => "Tezos",
		"XUC" => "Exchange Union",
		"XVC" => "Vcash",
		"XVG" => "Verge",
		"XWC" => "WhiteCoin",
		"XYO" => "XYO Network",
		"XZC" => "ZCoin",
		"YEE" => "YEE",
		"YOC" => "Yocoin",
		"YOYOW" => "YOYOW",
		"YTN" => "YENTEN",
		"YUP" => "Crowdholding",
		"ZAP" => "Zap",
		"ZBC" => "Zilbercoin",
		"ZCL" => "ZClassic",
		"ZCN" => "0chain",
		"ZCO" => "Zebi",
		"ZEC" => "Zcash",
		"ZEIT" => "Zeitcoin",
		"ZEN" => "ZenCash",
		"ZENGOLD" => "ZenGold",
		"ZENI" => "Zennies",
		"ZEPH" => "Zephyr",
		"ZER" => "Zero",
		"ZET" => "Zetacoin",
		"ZIL" => "Zilliqa",
		"ZINC" => "ZINC",
		"ZIP" => "Zipper",
		"ZIPT" => "Zippie",
		"ZLA" => "Zilla",
		"ZMC" => "ZetaMicron",
		"ZNY" => "Bitzeny",
		"ZOI" => "Zoin",
		"ZPR" => "ZPER token",
		"ZPT" => "Zeepin",
		"ZRC" => "ZrCoin",
		"ZRX" => "0x",
		"ZSC" => "Zeusshield",
		"ZSE" => "ZSEcoin",
		"ZUR" => "Zurcoin",
		"ZXC" => "0xcert",
		"ZYD" => "Zayedcoin",
		"ZZC" => "ZoZoCoin"
	);
	return $coin_matching_dict[$coin];
}

function country_code_to_name($code) {
	$code_matching_dict = array(
	"AF"=> "AFGHANISTAN",
	"AX"=> "ALAND_ISLANDS",
	"AL"=> "ALBANIA",
	"DZ"=> "ALGERIA",
	"AS"=> "AMERICAN_SAMOA",
	"AD"=> "ANDORRA",
	"AO"=> "ANGOLA",
	"AI"=> "ANGUILLA",
	"AG"=> "ANTIGUA",
	"AR"=> "ARGENTINA",
	"AM"=> "ARMENIA",
	"AW"=> "ARUBA",
	"AU"=> "AUSTRALIA",
	"AT"=> "AUSTRIA",
	"AZ"=> "AZERBAIJAN",
	"BS"=> "BAHAMAS",
	"BH"=> "BAHRAIN",
	"BD"=> "BANGLADESH",
	"BB"=> "BARBADOS",
	"BY"=> "BELARUS",
	"BE"=> "BELGIUM",
	"BZ"=> "BELIZE",
	"BJ"=> "BENIN",
	"BM"=> "BERMUDA",
	"BT"=> "BHUTAN",
	"BO"=> "BOLIVIA",
	"BA"=> "BOSNIA",
	"BW"=> "BOTSWANA",
	"BV"=> "BOUVET_ISLAND",
	"BR"=> "BRAZIL",
	"IO"=> "BRITISH_INDIAN_OCEAN_TERRITORY",
	"BN"=> "BRUNEI_DARUSSALAM",
	"BG"=> "BULGARIA",
	"BF"=> "BURKINA_FASO",
	"BI"=> "BURUNDI",
	"CV"=> "CABO_VERDE",
	"KH"=> "CAMBODIA",
	"CM"=> "CAMEROON",
	"CA"=> "CANADA",
	"KY"=> "CAYMAN_ISLANDS",
	"CF"=> "CENTRAL_AFRICAN_REPUBLIC",
	"TD"=> "CHAD",
	"CL"=> "CHILE",
	"CN"=> "CHINA",
	"CX"=> "CHRISTMAS_ISLAND",
	"CC"=> "COCOS_ISLANDS",
	"CO"=> "COLOMBIA",
	"KM"=> "COMOROS",
	"CD"=> "CONGO_REPUBLIC",
	"CG"=> "CONGO",
	"CK"=> "COOK_ISLANDS",
	"CR"=> "COSTA_RICA",
	"CI"=> "COTE_DIVOIRE",
	"HR"=> "CROATIA",
	"CU"=> "CUBA",
	"CW"=> "CURACAO",
	"CY"=> "CYPRUS",
	"CZ"=> "CZECH_REPUBLIC",
	"DK"=> "DENMARK",
	"DJ"=> "DJIBOUTI",
	"DM"=> "DOMINICA",
	"DO"=> "DOMINICAN_REPUBLIC",
	"EC"=> "ECUADOR",
	"EG"=> "EGYPT",
	"SV"=> "EL_SALVADOR",
	"GQ"=> "EQUATORIAL_GUINEA",
	"ER"=> "ERITREA",
	"EE"=> "ESTONIA",
	"ET"=> "ETHIOPIA",
	"FK"=> "FALKLAND_ISLANDS",
	"FO"=> "FAROE_ISLANDS",
	"FJ"=> "FIJI",
	"FI"=> "FINLAND",
	"FR"=> "FRANCE",
	"GF"=> "FRENCH_GUIANA",
	"PF"=> "FRENCH_POLYNESIA",
	"TF"=> "FRENCH_SOUTHERN_TERRITORIES",
	"GA"=> "GABON",
	"GB"=> "GREAT_BRITAIN",
	"GM"=> "GAMBIA",
	"GE"=> "GEORGIA",
	"DE"=> "GERMANY",
	"GH"=> "GHANA",
	"GI"=> "GIBRALTAR",
	"GR"=> "GREECE",
	"GL"=> "GREENLAND",
	"GD"=> "GRENADA",
	"GP"=> "GUADELOUPE",
	"GU"=> "GUAM",
	"GT"=> "GUATEMALA",
	"GG"=> "GUERNSEY",
	"GN"=> "GUINEA",
	"GW"=> "GUINEA_BISSAU",
	"GY"=> "GUYANA",
	"HT"=> "HAITI",
	"VA"=> "HOLY_SEE",
	"HN"=> "HONDURAS",
	"HK"=> "HONG_KONG",
	"HU"=> "HUNGARY",
	"IS"=> "ICELAND",
	"IN"=> "INDIA",
	"ID"=> "INDONESIA",
	"IR"=> "IRAN",
	"IQ"=> "IRAQ",
	"IE"=> "IRELAND",
	"IM"=> "ISLE_OF_MAN",
	"IL"=> "ISRAEL",
	"IT"=> "ITALY",
	"JM"=> "JAMAICA",
	"JP"=> "JAPAN",
	"JE"=> "JERSEY",
	"JO"=> "JORDAN",
	"KZ"=> "KAZAKHSTAN",
	"KE"=> "KENYA",
	"KI"=> "KIRIBATI",
	"KP"=> "NORTH_KOREA",
	"KR"=> "SOUTH_KOREA",
	"KW"=> "KUWAIT",
	"KG"=> "KYRGYZSTAN",
	"LA"=> "LAO",
	"LV"=> "LATVIA",
	"LB"=> "LEBANON",
	"LS"=> "LESOTHO",
	"LR"=> "LIBERIA",
	"LY"=> "LIBYA",
	"LI"=> "LIECHTENSTEIN",
	"LT"=> "LITHUANIA",
	"LU"=> "LUXEMBOURG",
	"MO"=> "MACAO",
	"MK"=> "MACEDONIA",
	"MG"=> "MADAGASCAR",
	"MW"=> "MALAWI",
	"MY"=> "MALAYSIA",
	"MV"=> "MALDIVES",
	"ML"=> "MALI",
	"MT"=> "MALTA",
	"MH"=> "MARSHALL_ISLANDS",
	"MQ"=> "MARTINIQUE",
	"MR"=> "MAURITANIA",
	"MU"=> "MAURITIUS",
	"YT"=> "MAYOTTE",
	"MX"=> "MEXICO",
	"FM"=> "MICRONESIA",
	"MD"=> "MOLDOVA",
	"MC"=> "MONACO",
	"MN"=> "MONGOLIA",
	"ME"=> "MONTENEGRO",
	"MS"=> "MONTSERRAT",
	"MA"=> "MOROCCO",
	"MZ"=> "MOZAMBIQUE",
	"MM"=> "MYANMAR",
	"NA"=> "NAMIBIA",
	"NR"=> "NAURU",
	"NP"=> "NEPAL",
	"NL"=> "NETHERLANDS",
	"NC"=> "NEW_CALEDONIA",
	"NZ"=> "NEW_ZEALAND",
	"NI"=> "NICARAGUA",
	"NE"=> "NIGER",
	"NG"=> "NIGERIA",
	"NU"=> "NIUE",
	"NF"=> "NORFOLK_ISLAND",
	"MP"=> "NORTHERN_MARIANA_ISLANDS",
	"NO"=> "NORWAY",
	"OM"=> "OMAN",
	"PK"=> "PAKISTAN",
	"PW"=> "PALAU",
	"PA"=> "PANAMA",
	"PG"=> "PAPUA_NEW_GUINEA",
	"PY"=> "PARAGUAY",
	"PE"=> "PERU",
	"PH"=> "PHILIPPINES",
	"PN"=> "PITCAIRN",
	"PL"=> "POLAND",
	"PT"=> "PORTUGAL",
	"PR"=> "PUERTO_RICO",
	"QA"=> "QATAR",
	"RE"=> "REUNION",
	"RO"=> "ROMANIA",
	"RU"=> "RUSSIA",
	"RW"=> "RWANDA",
	"BL"=> "SAINT_BARTHELEMY",
	"SH"=> "SAINT_HELENA",
	"KN"=> "SAINT_KITTS",
	"LC"=> "SAINT_LUCIA",
	"MF"=> "SAINT_MARTIN",
	"PM"=> "SAINT_PIERRE",
	"VC"=> "SAINT_VINCENT",
	"WS"=> "SAMOA",
	"SM"=> "SAN_MARINO",
	"ST"=> "SAO_TOME",
	"SA"=> "SAUDI_ARABIA",
	"SN"=> "SENEGAL",
	"RS"=> "SERBIA",
	"SC"=> "SEYCHELLES",
	"SL"=> "SIERRA_LEONE",
	"SG"=> "SINGAPORE",
	"SX"=> "SINT_MAARTEN",
	"SK"=> "SLOVAKIA",
	"SI"=> "SLOVENIA",
	"SB"=> "SOLOMON_ISLANDS",
	"SO"=> "SOMALIA",
	"ZA"=> "SOUTH_AFRICA",
	"SD"=> "SOUTH_SUDAN",
	"ES"=> "SPAIN",
	"LK"=> "SRI_LANKA",
	"SD"=> "SUDAN",
	"SR"=> "SURINAME",
	"SJ"=> "SVALBARD",
	"SZ"=> "SWAZILAND",
	"SE"=> "SWEDEN",
	"CH"=> "SWITZERLAND",
	"SY"=> "SYRIAN_ARAB_REPUBLIC",
	"TW"=> "TAIWAN",
	"TJ"=> "TAJIKISTAN",
	"TZ"=> "TANZANIA",
	"TH"=> "THAILAND",
	"TL"=> "TIMOR_LESTE",
	"TG"=> "TOGO",
	"TK"=> "TOKELAU",
	"TO"=> "TONGA",
	"TT"=> "TRINIDAD",
	"TN"=> "TUNISIA",
	"TR"=> "TURKEY",
	"TM"=> "TURKMENISTAN",
	"TC"=> "TURKS_AND_CAICOS_ISLANDS",
	"TV"=> "TUVALU",
	"UG"=> "UGANDA",
	"UA"=> "UKRAINE",
	"AE"=> "UNITED_ARAB_EMIRATES",
	"UK"=> "UNITED_KINGDOM",
	"US"=> "UNITED_STATES",
	"UY"=> "URUGUAY",
	"UZ"=> "UZBEKISTAN",
	"VU"=> "VANUATU",
	"VE"=> "VENEZUELA",
	"VN"=> "VIETNAM",
	"VG"=> "VIRGIN_ISLANDS_BRITISH",
	"VI"=> "VIRGIN_ISLANDS_US",
	"WF"=> "WALLIS_AND_FUTUNA",
	"EH"=> "WESTERN_SAHARA",
	"YE"=> "YEMEN",
	"ZM"=> "ZAMBIA",
	"ZW"=> "ZIMBABWE"
);

	return $code_matching_dict[$code];

}

function loadFile($url) {
  $ch = curl_init();

  curl_setopt($ch, CURLOPT_HEADER, 0);
  curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
  curl_setopt($ch, CURLOPT_URL, $url);

  $data = curl_exec($ch);
  curl_close($ch);

  return $data;
}
